server:
  port: 3001

spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    schema: classpath:db/schema.sql
    initialization-mode: always
    url: jdbc:h2:file:./data/data;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: admin
    password: admin666
  h2:
    console:
      #开启web console功能
      enabled: true
      settings:
        web-allow-others: false

logging:
  level:
    root: info
    org.springframework: error
  config: classpath:logback-spring.xml
  file:
    path: ./data/log

#mybatis-plus:
#  configuration:
#    # sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
