server:
  port: 3001

spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    schema: classpath:db/schema.sql
    initialization-mode: always
    url: jdbc:h2:file:./data/data;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username:
    password:
  h2:
    console:
      #开启web console功能
      enabled: true

logging:
  level:
    root: info
    org.springframework: error
  config: classpath:logback-spring.xml
  file:
    path: ./data/log

#mybatis-plus:
#  configuration:
#    # sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

docs-parser:
  # 文档名称
  docsName: XX接口文档
  # 文档版本
  version: V1.0
  # 启动时是否解析 true/false
  sysStartParse: false
  # java文件所在目录绝对路径（必须写到java目录，多个用英文逗号分隔）
  javaFilePaths: D:/test-project/src/main/java
  # 仅扫描解析该包集合下的controller类（必须位于javaFilePaths下，若不配置默认扫描javaFilePaths下所有，多个用英文逗号分隔）
  filterPackages: com.test
  # 仅扫描的controller类名集（非类全名，多个用英文逗号分隔）
  filterClassNames:
  # 需要排除的controller类名集（非类全名，多个用英文逗号分隔）
  ignoreClassNames:
  # 执行解析秘钥（在页面端请求解析接口需要携带该执行解析秘钥）
  apiRunKey: 123456
